
spring:
  profiles:
    active: local # 기본 환경 선택
  jpa:
    hibernate:
      use-new-id-generator-mappings: false # Hibernate의 id 생성 전략을 따라갈지 결정하는 useNewIdGeneratorMappings 설정. 2.0부터는 true가 기본값. -> auto increment가 잘 안먹히게됨  *참조 : https://jojoldu.tistory.com/295

# 카카오 앱소유계정 kidless@hanmail.net 
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <your client id>
            client-secret: <your client secret>
          facebook:
            client-id: <your client id>
            client-secret: <your client secret>
          kakao:
            client-id: <your client id>
            client-secret: <your client secret>
      
  # DATA WEB (SpringDataWebProperties)
  data:
    web:
      sort:
        sort-parameter: sort # Sort parameter name.
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

