server:
  port: 3000

# local 환경
---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql # 시작할때 실행시킬 script
  jpa:
    show-sql: true # JPA로 생성되는 쿼리 확인
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console # h2 db 웹 클라이언트 접속 url
  devtools:
    livereload:
      enabled: true # 정적파일들의 실시간 갱신. thymeleaf 템플릿의 변경 내용 실시간 반영
logging:
  level:
    org.springframework.web: TRACE
    org.hibernate.type: TRACE  # JPA로 생성되는 쿼리의 파라미터 값 확인
    org.thymeleaf: TRACE
    org.thymeleaf.TemplateEngine.CONFIG: TRACE